adding monero provider
YouToken/bc-listener pull request #22
Opened 2021-10-01 05:25 UTC by flasher007

2021-11-03 08:08 UTC, bifot approved these changes

2021-11-03 08:08 UTC, bifot commented on providers/xmr/clients/rest.js
> +      return request
используй async/await

2021-11-03 08:08 UTC, bifot commented on providers/xmr/clients/rest.js
> +    if (command === 'getHeight') {
команды вынеси в константы

2021-11-03 08:08 UTC, bifot commented on providers/xmr/clients/rest.js
> +const request = require('superagent');
используй что-то одно, здесь superagent, а в rpc - axios

2021-11-03 08:08 UTC, bifot commented on providers/xmr/clients/rest.js
> +    }
пропущена `;`

2021-11-03 08:08 UTC, bifot commented on providers/xmr/clients/rest.js
> +    let block = await this.cmd('getblock', height);
let -> const

2021-11-03 08:08 UTC, bifot commented on providers/xmr/clients/rest.js
> +    let block = await this.cmd('getblock', height);
getblock команду в контсанты

2021-11-03 08:08 UTC, bifot commented on providers/xmr/clients/rpc.js
> +        .post(`${this.walletUrl}/json_rpc`, JSON.stringify({
не нужно делать `JSON.stringify`, в axios это сделается само

2021-11-03 08:08 UTC, bifot commented on providers/xmr/clients/rpc.js
> +          jsonrpc: "2.0",
то двойные, то одинарные кавычки, приведи к единому виду (одинарные в файле)

2021-11-03 08:08 UTC, bifot commented on providers/xmr/clients/rpc.js
> +          headers: {
заголовки здесь не нужны, axios их сам отправит

2021-11-03 08:08 UTC, bifot commented on providers/xmr/clients/rpc.js
> +      console.error(e);
а как мы эти ошибки хендлить будем? здесь не будет ни времени, ни версии, ничего в логах, мы так не делаем

2021-11-03 08:08 UTC, bifot commented on providers/xmr/clients/rpc.js
> +      return _.get(res, 'data.result');
от axios можно делать деструктуризацию, здесь не нужен lodash:

```js
const { data } = await axios.get(...);

return data.result;
```

2021-11-03 08:08 UTC, bifot commented on providers/xmr/clients/rpc.js
> +'use strict';
отступ после 'use strict'

2021-11-03 08:08 UTC, bifot commented on providers/xmr/clients/rest.js
> +'use strict';
отступ после 'use strict'

2021-11-03 08:08 UTC, bifot commented on providers/xmr/clients/rpc.js
> +          id: new Date().getTime()
а если мы отправим несколько запросов в одну мс?

2021-11-03 08:08 UTC, bifot commented on providers/xmr/index.js
> +  constructor(options) {
в рамках ветки у тебя 3 класса, и опять по-разному, здесь есть отступ перед конструктором, в остальных двух нет, удали здесь отступ

2021-11-03 08:08 UTC, bifot commented on providers/xmr/index.js
> +};
здесь не нужна `;`

2021-11-03 08:08 UTC, bifot commented on providers/xmr/index.js
> +    return this.clientRest.getBlock(height);
везде, где юзаешь async/await и вызываешь новую функцию асинхронную, ставь `return await this.clientRest.getBlock(...)`, чтоб стактрейс при ошибках был более подробный

2021-11-03 08:08 UTC, bifot commented on providers/xmr/index.js
> +    return this.clientRest.getCurrentHeight();
`return await`

2021-11-03 08:08 UTC, bifot commented on providers/xmr/index.js
> +    return this.clientRpc.request({method, params});
`return await`

2021-11-04 12:07 UTC, flasher007 commented on providers/xmr/clients/rpc.js
> +          id: new Date().getTime()
не страшно)

2021-11-04 12:07 UTC, flasher007 commented on providers/xmr/index.js
> +};
нужна же)

2021-11-04 12:19 UTC, bifot commented on providers/xmr/index.js
> +};
https://eslint.org/docs/rules/no-extra-semi

2021-11-15 11:02 UTC, bifot requested changes

2021-11-15 11:02 UTC, bifot commented on providers/xmr/clients/rpc.js
> +      return null;
а где обработка ошибок?

2026-04-05 20:01 UTC, closed without merging